# Generated by Django 5.2 on 2025-10-14 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_fornecedor', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Fornecedor')),
                ('nome_fornecedor', models.TextField(db_index=True, verbose_name='Nome do Fornecedor')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores',
                'indexes': [models.Index(fields=['nome_fornecedor'], name='fornecedore_nome_fo_f3f770_idx'), models.Index(fields=['active'], name='fornecedore_active_d2f35a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('cod_sku', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código SKU')),
                ('descricao_item', models.TextField(db_index=True, verbose_name='Descrição do Item')),
                ('unid_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'itens',
                'indexes': [models.Index(fields=['descricao_item'], name='itens_descric_50f56a_idx'), models.Index(fields=['active'], name='itens_active_7490f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('cod_nf', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código da Nota Fiscal')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantidade')),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitário')),
                ('cod_fornecedor', models.ForeignKey(blank=True, db_column='cod_fornecedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.fornecedor', verbose_name='Fornecedor')),
                ('cod_sku', models.ForeignKey(db_column='cod_sku', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'transacoes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('mat_usuario', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Matrícula do Usuário')),
                ('nome_usuario', models.TextField(verbose_name='Nome do Usuário')),
                ('permissions', models.JSONField(blank=True, default=list, null=True, verbose_name='Permissões')),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Autenticação')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('cod_pedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Código do Pedido')),
                ('data_saida', models.DateField(db_index=True, verbose_name='Data da Saída')),
                ('hora_saida', models.TimeField(verbose_name='Hora da Saída')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='inventory.transacao', verbose_name='Transação')),
                ('mat_usuario', models.ForeignKey(db_column='mat_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'db_table': 'saidas',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('cod_entrada', models.AutoField(primary_key=True, serialize=False, verbose_name='Código da Entrada')),
                ('data_entrada', models.DateField(db_index=True, verbose_name='Data da Entrada')),
                ('hora_entrada', models.TimeField(verbose_name='Hora da Entrada')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='inventory.transacao', verbose_name='Transação')),
                ('mat_usuario', models.ForeignKey(db_column='mat_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entradas',
            },
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['cod_nf'], name='transacoes_cod_nf_0980ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['cod_sku'], name='transacoes_cod_sku_514ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['cod_fornecedor'], name='transacoes_cod_for_dcf6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['data_saida'], name='saidas_data_sa_f43733_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['transacao'], name='saidas_transac_894ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['mat_usuario'], name='saidas_mat_usu_c0f269_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['data_entrada'], name='entradas_data_en_b931de_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['transacao'], name='entradas_transac_62b9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['mat_usuario'], name='entradas_mat_usu_b7c3a1_idx'),
        ),
    ]
