# Generated by Django 5.2 on 2025-05-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_active_to_fornecedor'),
        ('inventory', '0003_item_active'),
    ]

    operations = [
    ]
