# Generated by Django 5.2 on 2025-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_0002_add_active_to_fornecedor_0003_item_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='active',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cod_fornecedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
