# Generated by Django 5.2 on 2025-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_change_fornecedor_id_to_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
