# Generated by Django 5.2 on 2025-05-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_active_to_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='cod_fornecedor',
            field=models.ForeignKey(db_column='cod_fornecedor', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.fornecedor'),
            preserve_default=False,
        ),
    ]
