# Generated by Django 5.2 on 2025-05-09 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_usuario_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='cod_nf',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='cod_sku',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='qtd_saida',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cod_entrada',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saida',
            name='cod_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('cod_nf', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_sku', models.DecimalField(decimal_places=0, max_digits=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cod_fornecedor', models.ForeignKey(blank=True, db_column='cod_fornecedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.fornecedor')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'projinteg.transacoes',
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='transacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='inventory.transacao'),
        ),
        migrations.AddField(
            model_name='saida',
            name='transacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='inventory.transacao'),
        ),
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
    ]
