# Generated by Django 5.2 on 2025-05-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_entrada_cod_nf_remove_saida_cod_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='inventory.transacao'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='inventory.transacao'),
        ),
    ]
