# Generated by Django 5.2 on 2025-05-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_entrada_transacao_alter_saida_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='cod_sku',
            field=models.ForeignKey(db_column='cod_sku', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item'),
        ),
    ]
