# Generated by Django 5.2 on 2025-05-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_transacao_cod_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='data_entrada',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fornecedor',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao_item',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='saida',
            name='data_saida',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='cod_nf',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['data_entrada'], name='projinteg.e_data_en_705069_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['transacao'], name='projinteg.e_transac_0a800f_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['nome_fornecedor'], name='projinteg.f_nome_fo_c5f9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['descricao_item'], name='projinteg.i_descric_a33e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['data_saida'], name='projinteg.s_data_sa_5cfe9d_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['transacao'], name='projinteg.s_transac_fa28f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transacao',
            index=models.Index(fields=['cod_nf'], name='projinteg.t_cod_nf_491cf6_idx'),
        ),
    ]
