# Generated by Django 5.2 on 2025-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_entrada_data_entrada_alter_fornecedor_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
