# Generated by Django 5.2 on 2025-05-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_usuario_permissions'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE SCHEMA IF NOT EXISTS "projinteg";
            
            CREATE TABLE IF NOT EXISTS "projinteg"."usuarios" (
                mat_usuario BIGINT PRIMARY KEY,
                nome_usuario TEXT NOT NULL,
                auth_user_id INTEGER NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                permissions JSONB NULL DEFAULT '[]'::jsonb
            );
            
            CREATE INDEX IF NOT EXISTS usuarios_auth_user_id_idx ON "projinteg"."usuarios"(auth_user_id);
            
            -- Transferir dados se a tabela public.usuarios existir
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'usuarios'
                ) THEN
                    INSERT INTO "projinteg"."usuarios" (mat_usuario, nome_usuario, auth_user_id, permissions)
                    SELECT mat_usuario, nome_usuario, auth_user_id, permissions 
                    FROM public.usuarios
                    ON CONFLICT (mat_usuario) DO NOTHING;
                    
                    DROP TABLE public.usuarios;
                END IF;
            END
            $$;
            """,
            
            # SQL para reversão (rollback) da migração
            """
            DROP TABLE IF EXISTS "projinteg"."usuarios";
            """
        ),
    ]
