# Generated by Django 5.2 on 2025-05-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0014_recreate_usuario_table'),
    ]

    operations = [
        # Passo 1: Remover a tabela usuarios se ela existir
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS "projinteg"."usuarios";
            """,
            reverse_sql="""
            -- Não fazer nada ao reverter
            """
        ),
        
        # Passo 2: Criar um schema se ainda não existir
        migrations.RunSQL(
            """
            CREATE SCHEMA IF NOT EXISTS "projinteg";
            """,
            reverse_sql="""
            -- Não fazer nada ao reverter
            """
        ),
        
        # Passo 3: Criar a tabela Usuario manualmente
        migrations.CreateModel(
            name='UsuarioRebuilt',
            fields=[
                ('mat_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_usuario', models.TextField()),
                ('permissions', models.JSONField(blank=True, default=list, null=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_user_new', to='auth.user')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'projinteg\".\"usuarios',
            },
        ),
        
        # Passo 4: Uma migração final para vincular o auth_user aos usuarios existentes (se houver)
        migrations.RunSQL(
            """
            -- Transferir permissões do modelo antigo para o novo se existirem
            DO $$
            BEGIN
                UPDATE "projinteg"."usuarios" SET auth_user_id = u.id
                FROM auth_user u
                WHERE u.username = "projinteg"."usuarios".nome_usuario
                AND "projinteg"."usuarios".auth_user_id IS NULL;
            EXCEPTION
                WHEN undefined_table THEN NULL;
            END
            $$;
            """,
            reverse_sql="""
            -- Não fazer nada ao reverter
            """
        ),
    ]
