# Generated by Django 5.2 on 2025-09-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_recreate_usuario_table_2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='projinteg.usuarios',
        ),
        migrations.DeleteModel(
            name='UsuarioRebuilt',
        ),
    ]
