# Generated by Django 5.2 on 2025-09-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_usuario_table_delete_usuariorebuilt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='projinteg.usuarios',
        ),
    ]
