# Generated by Django 5.2 on 2025-09-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_usuario_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entrada',
            new_name='entradas_data_en_b931de_idx',
            old_name='projinteg.e_data_en_705069_idx',
        ),
        migrations.RenameIndex(
            model_name='entrada',
            new_name='entradas_transac_62b9f9_idx',
            old_name='projinteg.e_transac_0a800f_idx',
        ),
        migrations.RenameIndex(
            model_name='fornecedor',
            new_name='fornecedore_nome_fo_f3f770_idx',
            old_name='projinteg.f_nome_fo_c5f9a4_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='itens_descric_50f56a_idx',
            old_name='projinteg.i_descric_a33e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='saida',
            new_name='saidas_data_sa_f43733_idx',
            old_name='projinteg.s_data_sa_5cfe9d_idx',
        ),
        migrations.RenameIndex(
            model_name='saida',
            new_name='saidas_transac_894ba6_idx',
            old_name='projinteg.s_transac_fa28f4_idx',
        ),
        migrations.RenameIndex(
            model_name='transacao',
            new_name='transacoes_cod_nf_0980ec_idx',
            old_name='projinteg.t_cod_nf_491cf6_idx',
        ),
        migrations.AlterModelTable(
            name='entrada',
            table='entradas',
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedores',
        ),
        migrations.AlterModelTable(
            name='item',
            table='itens',
        ),
        migrations.AlterModelTable(
            name='saida',
            table='saidas',
        ),
        migrations.AlterModelTable(
            name='transacao',
            table='transacoes',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
