# Generated by Django 5.2 on 2025-04-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_fornecedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.TextField()),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'projinteg.fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('cod_sku', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao_item', models.TextField()),
                ('unid_medida', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'projinteg.itens',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('cod_nf', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cod_sku', models.DecimalField(decimal_places=0, max_digits=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'db_table': 'projinteg.notas_fiscais',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('mat_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_usuario', models.TextField()),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'projinteg.usuarios',
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('cod_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('qtd_saida', models.BigIntegerField()),
                ('data_saida', models.DateField()),
                ('hora_saida', models.TimeField()),
                ('cod_sku', models.ForeignKey(db_column='cod_sku', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('mat_usuario', models.ForeignKey(db_column='mat_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.usuario')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'db_table': 'projinteg.saidas',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('cod_entrada', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('cod_nf', models.ForeignKey(db_column='cod_nf', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.notafiscal')),
                ('mat_usuario', models.ForeignKey(db_column='mat_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.usuario')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'projinteg.entradas',
            },
        ),
    ]
