# Generated by Django 5.2 on 2025-05-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cod_sku',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
